// POST /api/reserve-track — first-party analytics collector for /reserve/.
//
// The portal page beacons here twice at most: once on arrival ("view") and
// once if a venue is chosen ("click"). Public and unauthenticated by
// necessity — real visitors have no credentials — so everything that could
// identify or be spoofed is derived SERVER-side from the request itself
// (country, city, device, browser). The client only supplies things the server
// cannot see: which venue was clicked, its page-load nonce, the referrer, and
// the UTM tags off its own URL.
//
// See functions/data/reserve-track.ts for what is stored and why it needs no
// cookie consent. Reads live behind Cloudflare Access at /admin/reserve/.

import type { PagesFunction } from '@cloudflare/workers-types';
import {
  recordHit, deviceClass, browserFamily, looksLikeBot, referrerHost,
  type Hit, type ReserveTrackEnv, type ReserveVenue,
} from '../data/reserve-track';

type Env = ReserveTrackEnv;

/** 204 with no body — the beacon never reads a response, and an empty one
 *  keeps the request cheap on mobile connections. */
function accepted(): Response {
  return new Response(null, { status: 204, headers: { 'Cache-Control': 'no-store' } });
}

interface Body {
  e?:  unknown;
  v?:  unknown;
  s?:  unknown;
  r?:  unknown;
  us?: unknown;
  um?: unknown;
  uc?: unknown;
}

/** Trim client-supplied strings hard. KV metadata is capped at 1024 bytes per
 *  key, and no legitimate value here is long. */
function str(v: unknown, max: number): string {
  return typeof v === 'string' ? v.trim().slice(0, max) : '';
}

export const onRequestPost: PagesFunction<Env> = async ({ request, env }) => {
  const url = new URL(request.url);
  const ua  = request.headers.get('User-Agent') || '';

  // Every failure below still answers 204. A tracking beacon must never
  // surface an error to the visitor, and a 4xx would only tell an abuser
  // which payloads are being rejected.
  if (looksLikeBot(ua)) return accepted();

  // Same-origin only. Browsers set Origin on beacons and cannot be made to
  // forge it, so this drops casual cross-site pollution. (It stops a browser,
  // not a script — the real backstop is the 90-day TTL on every key.)
  const origin = request.headers.get('Origin');
  if (origin) {
    try {
      if (new URL(origin).host !== url.host) return accepted();
    } catch {
      return accepted();
    }
  }

  let body: Body;
  try {
    body = (await request.json()) as Body;
  } catch {
    return accepted();
  }

  const e = body.e === 'click' ? 'click' : body.e === 'view' ? 'view' : null;
  if (!e) return accepted();

  // The nonce is generated by the page; anything that isn't the expected shape
  // is dropped rather than stored, so it can't be used to smuggle in an id.
  const s = str(body.s, 16);
  if (!/^[a-z0-9]{6,16}$/.test(s)) return accepted();

  const venue: ReserveVenue | undefined =
    e === 'click' ? (body.v === 'rooftop' ? 'rooftop' : 'zahara') : undefined;

  const cf = request.cf;

  const hit: Hit = {
    e,
    t: Date.now(),
    s,
    ...(venue ? { v: venue } : {}),
    c:  str(cf?.country as string | undefined, 4),
    ct: str(cf?.city    as string | undefined, 48),
    d:  deviceClass(ua),
    b:  browserFamily(ua),
    r:  referrerHost(str(body.r, 300), url.hostname),
    us: str(body.us, 48),
    um: str(body.um, 48),
    uc: str(body.uc, 64),
  };

  try {
    await recordHit(env, hit);
  } catch {
    /* KV unavailable or over quota — losing a hit must never break the page. */
  }

  return accepted();
};
